### ISSUE TITLE
Add actual "Glitch" category

### ISSUE THREAD

**Issue by frdmn** [gta5-map/gta5-map.github.io#2]

**Comment by frdmn** [comment]
- Walk under water glitch
- Gate glitches

**Comment by timelf123** [comment]
- wall breaches?

**Comment by frdmn** [comment]
@timelf123 We already have that category :)

**Comment by timelf123** [comment]
Should have looked before I posted! Nice work on the site btw

**Comment by frdmn** [comment]
@timelf123 Thank you! We perhaps just need an easier method to add new locations for users... I think the [current method](https://github.com/gta5-map/gta5-map.github.io/wiki/How-to-add-new-locations%3F) is still to time consuming :/

**Comment by frdmn** [comment]
Added in cdd38a25e46b676132cb830bd0eb0ffde2be5665, 81c9eb6f1f1ee89dacb0ecea5994721997b09a73 and da5db55e33a9435b219505858642ff00de04f733
